[package]
name = "project_euler"
version = "1.0.0"
authors = ["Divya Jain <divykjain@gmail.com>"]
edition = "2018"

[dependencies]
paste = "1.0.4"
webbrowser = "0.5.5"
structopt = "0.3.21"
clipboard = "0.5.0"
lazy_static = "1.4.0"
derive_more = "0.99.11"
sugars = "3.0.0"
itertools = "0.10.1"
